### Re-attach sample name to a genotype file
# The alleles file generated by rubias_to_alleles() ends up with a rubias ID, but losing the sample.name
# This script re-attaches the sample.name using the ES
# **Note**: not yet designed to handle any genetic sex except "0"

add_sample_name <- function(input_type = "allele", base = TRUE){
  
  # Read in the allele file
  alleles.FN <- choose.files(default = file.path(current.path), caption = "Select an allele file")
  alleles.df <-   read.delim(file = alleles.FN, header = T, sep = "\t"
                             , stringsAsFactors = F, colClasses = c("character") # necessary to prevent T convert to TRUE
                             )
  
  # Set the filename of input ES
  if(base==TRUE){
    
    ES.FN <- ES.base
    
  }else if(base==FALSE){
    
    ES.FN <- ES.mix
    
  }
  
  # Read in the extraction sheet (ES)
  print("Reading in extraction data")
  Exl_df <- read.delim(file = ES.FN, header = TRUE, sep = "\t", fill = TRUE, quote = ""
                       , stringsAsFactors = FALSE
                         )
  
  # Convert 0s to "U"
  Exl_df[is.na(Exl_df$Sex), "Sex"] <- "U"
  Exl_df[Exl_df$Sex==0, "Sex"] <- "U"
  
  # Create connector column in ES
  Exl_df$rubias.id<- paste0(Exl_df$StockCode, "_", Exl_df$Year, "_", Exl_df$Fish, "_", Exl_df$Sex)
  
  # Keep only relevant to attach
  Exl_df <- Exl_df[,c("Sample_ID", "rubias.id")]
  
  # Reporting
  print(paste0("Keeping data for ", length(intersect(alleles.df$indiv, Exl_df$rubias.id)), " individuals"))
  
  # Connect the two df
  alleles_and_ES.df <- merge(x = Exl_df, y = alleles.df, by.x= "rubias.id", by.y = "indiv"
                             , all.y = TRUE
                             )
  
  # Write output
  write.FN <- gsub(pattern = ".txt", replacement = "_add_sample_name.txt", x = alleles.FN)
  print(paste0("The allele file will be written to ", write.FN))
  write.table(alleles_and_ES.df, file = write.FN, col.names = T, row.names = F, sep = "\t",quote = F)
  
}
  
  