# Relatedness simulations

# Allele frequencies are generated by coancestry() fn
head(output$freqs)

# Simulate known relatedness individuals
sim <- familysim(freqs = output$freqs, ninds = 5)

## Currently crashing, not able to run on Linux

# 
#grouprel not existant anymore?